### ISSUE TITLE
Colors are shifted for PDF-files containing images with a color profile other than RGB

### ISSUE THREAD

**Issue by a8w4** [BWPanda/pdf_to_image#3] opened 2021-06-13 11:56 UTC
Please compare especially the color of the green header in the appended sample files:
[wih--mai-2021.pdf](https://github.com/backdrop-contrib/pdf_to_image/files/6643825/wih--mai-2021.pdf)
[wih--mai-2021-0.jpg](https://user-images.githubusercontent.com/2727863/121806141-013a1b00-cc4f-11eb-981e-1031c4092398.jpg)

I fixed this issue now as requested in #5  by enforcing the sRGB color space - which doesn't seem to hurt the extraction of PDFs with a RGB color space in any way  - but I'm no expert on this topic.

[Here](https://stackoverflow.com/questions/64608519/convert-cmyk-pdf-to-srgb-jpg-using-php-and-imagick) the same problem and solution are mentioned and another sample file is provided.

**Comment by indigoxela** [comment] 2021-07-25 08:38
Cool, one PR fixes one issue - that's much easier to handle. :+1: 

Yes, that's definitely a visible color shift. And images with a different color profile aren't uncommon in pdf files - as they're often supposed to get printed.

The code looks good to me, RTBC from my side.

**Comment by olafgrabienski** [comment] 2021-07-25 15:05
@a8w4 Many thanks for the PR! I was able to reproduce the issue using your PDF file. In my test environment, the PR fixes the header colors (green and red).

Unfortunately, as a side-effect, the background color of the first page turned from white to black (see below). Is this a matter of the environment? I've had a look at the PHP settings of my (shared) hosting environment: ImageMagick there doesn't seem to support the SRGB format. Not sure how common this setting is.

Without PR (colors in header wrong):
![wih--mai-2021-test-a](https://user-images.githubusercontent.com/14188307/126903813-1693571d-3e2a-4d91-bbbf-84dfba7de4b0.jpg)

With PR (header color correct, background color wrong):
![wih--mai-2021-test-b](https://user-images.githubusercontent.com/14188307/126903814-1b53a241-70d7-4c88-afaa-3b612af6ef92.jpg)

**Comment by indigoxela** [comment] 2021-07-26 06:24
Hm, odd, I can reproduce it on a server. It's not that srgb isn't supported, but it seems to depend on the image format you choose for output (jpeg - black / png - white).

This issue in the Drupal module issue queue *might* be related: https://www.drupal.org/project/pdf_to_imagefield/issues/2913750

Note: that actually seems to be an Imagemagick bug in combination with CMYK color format.

Time for version comparison:

On the server I could reproduce it: ImageMagick 6.9.10, PHP 7.4

**Comment by indigoxela** [comment] 2021-07-26 07:22
For what it's worth - this works for me:

```
    // Process the PDF file.
    $imagick = new imagick();
    $imagick->setResolution($settings['options']['resolution'], $settings['options']['resolution']);
    $imagick->setColorspace(Imagick::COLORSPACE_SRGB);
    $imagick->readImage($file->uri);

    if ($settings['format'] == 'jpg') {
      $imagick->mergeImageLayers(Imagick::LAYERMETHOD_FLATTEN);
      $imagick->setImageAlphaChannel(Imagick::ALPHACHANNEL_REMOVE);
    }

    $imagick->setImageFormat($settings['format']);
...
```
The colorspace still needs to be SRGB, but if it's a jpg (jpg has no alpha), we have to flatten and remove the alpha channel. I'm not 100% sure if this works the same with all Imagick versions, but it seems worth a try. @a8w4 and @olafgrabienski - willing to try it out?

**Comment by olafgrabienski** [comment] 2021-07-26 10:29
> ImageMagick 6.9.10, PHP 7.4

similar in my test environment: ImageMagick 6.9.10-23, PHP 7.4.19

**Comment by olafgrabienski** [comment] 2021-07-26 10:32
> if ($settings['format'] == 'jpg') {
      $imagick->mergeImageLayers(Imagick::LAYERMETHOD_FLATTEN);
      $imagick->setImageAlphaChannel(Imagick::ALPHACHANNEL_REMOVE);
    }

Great, works for me! (Well, using nearly the same ImageMagick version.)

**Comment by a8w4** [comment] 2021-07-26 18:38
@indigoxela [This idea](https://github.com/backdrop-contrib/pdf_to_image/issues/3#issuecomment-886446746) is genius - thank your for that! In my tests actually all three image file-types possible: PNG, GIF and JPG had transparent areas through which the background color in effect could bleed through. Therefore I removed the conditional from your code an pushed it in my PR  #5. (Since I am a still a GG [GitHub Greenhorn] - should I have created a new PR for that?) 
After these changes there was no black (actually transparent) background anymore anywhere. 
Also I believe that flattening the image and removing the alpha channel does no harm in 99.9999 % of cases, because I cannot imagine any reason, why one would want to let the background shine through images of PDF-Pages, or would need any layers.

**Comment by a8w4** [comment] 2021-07-26 18:45
PHP in use: 7.3.28-1+0
imagick module version: 3.4.4
ImageMagick library version:  6.9.10-23

**Comment by indigoxela** [comment] 2021-07-27 06:16
> all three image file-types possible: PNG, GIF and JPG had transparent areas through which the background color in effect could bleed through

Hm. I didn't see a problem with png, but that might depend on the actual pdf files.

> I am a still a GG [GitHub Greenhorn] - should I have created a new PR for that?

Additional commits are fine, as the PR gets stashed anyway, when merged. (GG - :smile: )

> I believe that flattening the image and removing the alpha channel does no harm in 99.9999 % of cases...

Seems plausible to me, but might need a little more testing. I'll try different things out to verify...

Further reading: https://www.prepressure.com/pdf/basics/transparency

**Comment by indigoxela** [comment] 2021-07-27 06:24
In the meantime some (picky) hints regarding coding standards... I hope this isn't too frustrating.

Comments shouldn't be any longer than 80 chars, should start with an uppercase letter and should end with "." (appropriate punctuation). That's not related to the code itself, just a coding standard. I assume that @BWPanda would ask for the same, anyway. :wink:

**Comment by indigoxela** [comment] 2021-07-27 06:30
Oh, and some helpful hint for the "GG":

In your PR description, if you change `fix for issue #3` to `Fixes #3`, GitHub will link the PR in this issue's header and close it, when the PR gets merged - automagically. :smiley:

**Comment by a8w4** [comment] 2021-07-27 06:46
Thanks for the hint - I was actually wondering, why the two weren't connected!

**Comment by indigoxela** [comment] 2021-07-27 08:36
Re our change for jpg images: I made sure that this doesn't cause any problems with a pdf with transparency - it doesn't. (I can provide the testing pdf I used.)

Re the idea to also strip out alpha and flatten for png and gif: IMO that's not necessary (no problem with gif or png) and it has a bad side effect: the file size increases significantly.

So, @a8w4 please consider wrapping in `if ($settings['format'] == 'jpg') {`.
That way we make sure, we only fix the actual problem - black backgrounds only appear in jpg's. Or do you have a pdf where this also happens with png or gif? If so, please provide it, so we can also test with it.

**Comment by a8w4** [comment] 2021-07-27 09:50
Thanks @indigoxela for investigating - but I am absolutely sure that the transparency problem exists for all three file types.
For me it was crucial to view the created image files directly from the file system - I am using Xviewer on Linux Mint: It shows clearly that the background is always transparent when the image is not flattened and the alpha channel exists be it GIF or PNG. Another way to verify this could be to set the background color of the containing div-tag to black. The provided file wih--mai-2021.pdf in the issue description can be used to reproduce my findings. It may also be the case that an active image-style fixes the problem coincidentally.

**Comment by a8w4** [comment] 2021-07-27 10:01
> Re our change for jpg images: I made sure that this doesn't cause any problems with a pdf with transparency - it doesn't. (I can provide the testing pdf I used.)

Am I understanding this right: this would be a pdf that uses transparency internally for it's elements?

**Comment by indigoxela** [comment] 2021-07-27 10:10
> ...but I am absolutely sure that the transparency problem exists for all three file types.

Can you provide a file that causes a black background with png/gif, please? Note: it's _not_ transparency, which causes us trouble, it's the conversion to **jpg** - a format that has no transparency.

IMO, if you want all transparency stripped, that should be a new issue. Let's stick with the color shift topic for CMYK here - complex enough for one issue. :smirk: 

> Am I understanding this right: this would be a pdf that uses transparency internally for it's elements?

Yes, since pdf version 1.4 they can contain transparency, but I didn't find any problems with our solution, all good.

**Comment by a8w4** [comment] 2021-07-27 13:59
> Can you provide a file that causes a black background with png/gif, please? 

No, I never had that case - they all had transparent backgrounds.

> Note: it's _not_ transparency, which causes us trouble, it's the conversion to **jpg** - a format that has no transparency.

OK, that's where our different views come from: I believed that transparency, which in my mind is not necessary anyways, was the root cause of the issue - I may be wrong... (I'll admit, I do have a penchant for a general solution ;-) )

> IMO, if you want all transparency stripped, that should be a new issue. Let's stick with the color shift topic for CMYK here - complex enough for one issue.

You're right, will do! Your way is less invasive and indeed avoids larger file sizes.
(If you wanted, you could also roll your own PR, as the number of code lines from you is already double than mine (2:1) ;-))

**Comment by indigoxela** [comment] 2021-07-27 15:22
> ...I do have a penchant for a general solution

I'm totally fine with that, but personally I'm a friend of step-by-step approaches. :smile: 

> If you wanted, you could also roll your own PR, as the number of code lines from you is already double than mine

Nah, never mind. You're on a roll, so keep on. :+1:

**Comment by a8w4** [comment] 2021-07-27 16:21
> Nah, never mind. You're on a roll, so keep on.

Thx, but you really have put a lot of effort in this - so thank's again for that!
The PR is updated - I hope, we're on the home stretch now...

**Comment by olafgrabienski** [comment] 2021-07-27 19:50
> The PR is updated - I hope, we're on the home stretch now...

Tested again, and works for me!

Regarding the discussion about transparency (no matter if in a new issue or here): If the background of the relevant web page part isn't white but e.g. black, a transparent PNG background is quite problematic. See the following example:

<img width="357" alt="backdrop-pdf2image-png-transparent-bg-black" src="https://user-images.githubusercontent.com/14188307/127218203-ae167210-16dc-4699-9676-586362bd03f4.png">

**Comment by indigoxela** [comment] 2021-07-28 06:15
Re the removal of transparency: I think, this should be a setting, because some people might prefer transparency, while others don't. IMO it should be a new issue, so we can properly discuss and evaluate the best solution. :smirk:

Regarding the current topic "color shift": Also works for me (I also tested with ImageMagick 7.0.7), the code looks good, RTBC!

**Comment by indigoxela** [comment] 2021-08-13 06:03
@backdrop-contrib/bug-squad it seems like this issue is now in a state to get merged by one of you.

It's marked as RTBC for 16 days now and the previous maintainer withdrew.

**Closed as completed** 2021-08-14 03:50 UTC
Labels: pr - ready to be committed, pr - works for me
